import ShapeNode from "../components/ShapeNode"; // ya jahan bhi file hai

export const nodeTypes = {
  // Original entries (unchanged)
  Task: ShapeNode,
  "Event Subprocesses": ShapeNode,
  "Sequence Flow": ShapeNode,
  Association: ShapeNode,
  "Data-based Exclusive(XOR) gateway": ShapeNode,
  "Start-event": ShapeNode,
  "end-event": ShapeNode,
  "Terminating End Event": ShapeNode,
  "Event-based Gateway": ShapeNode,
  "Parallel Gateway": ShapeNode,
  "Inclusive Gateway": ShapeNode,
  "Complex Gateway": ShapeNode,
  "Collapsed Subprocesses": ShapeNode,
  "Expanded Subprocesses": ShapeNode,
  "Collapsed Event-Subprocesses": ShapeNode,

  // New entries added
  Pool: ShapeNode,
  "Collapsed Pool": ShapeNode,
  Lane: ShapeNode,
  "Additional Participant": ShapeNode,
  Group: ShapeNode,
  "Text Annotation": ShapeNode,
  "IT System": ShapeNode,
  "Data Object": ShapeNode,
  "Data Store": ShapeNode,
  Message: ShapeNode,
  "Intermediate Message Event": ShapeNode,
  "Intermediate Timer Event": ShapeNode,
  "Intermediate Escalation Event": ShapeNode,
  "Intermediate Conditional Event": ShapeNode,
  "Intermediate Link Event": ShapeNode,
  "Intermediate Error Event": ShapeNode,
  "Intermediate Cancel Event": ShapeNode,
  "Intermediate Compensation Event": ShapeNode,
  "Intermediate Signal Event": ShapeNode,
  "Intermediate Multiple Event": ShapeNode,
  "Intermediate Parallel Multiple Event": ShapeNode,
  "Intermediate Event": ShapeNode,
  "Start Message Event": ShapeNode,
  "Start Timer Event": ShapeNode,
  "Start Escalation Event": ShapeNode,
  "Start Conditional Event": ShapeNode,
  "Start Error Event": ShapeNode,
  "Start Compensation Event": ShapeNode,
  "Start Signal Event": ShapeNode,
  "start Multiple Event": ShapeNode,
  "Start Parallel Multipe Event": ShapeNode,
  "End Message Event": ShapeNode,
  "End Escalation Event": ShapeNode,
  "End Error Event": ShapeNode,
  "Cancel End Event": ShapeNode,
  "End Compensation Event": ShapeNode,
  "End Signal Event": ShapeNode,
  "End Multiple Event": ShapeNode,
};
